services:
  nginx_proxy_manager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
       - 80:80
       - 443:443
       - 81:81
    volumes:
      - ./data/npm_data:/data
      - ./data/npm_letsencrypt:/etc/letsencrypt
      - ./data/npm_logs:/var/log/nginx
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      INITIAL_ADMIN_EMAIL: admin@example.com
      INITIAL_ADMIN_PASSWORD: changeme
    networks:
      - npm_proxy
      - nextcloud_network
      - immich_network
      - openwebui_network
      - vaultwarden_default

networks:
  npm_proxy:
    name: npm_proxy
    driver: bridge
  
  nextcloud_network:
    external: true
    name: nextcloud_default
  
  immich_network:
    external: true
    name: immich_default
  
  openwebui_network:
    external: true
    name: open-webui_default

  vaultwarden_default:
    external: true
    name: vaultwarden_default
