services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
      - JELLYFIN_PublishedServerUrl=https://jellyfin.tail.sargun.ca
    volumes:
      - ./library:/config
      - ./tvseries:/data/tvshows
      - ./music:/data/music
      - ./movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

networks:
  jellyfin_network:
    name: jellyfin_default
    driver: bridge
