services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: ./music
        target: /data/music
      - type: bind
        source: ./anime
        target: /data/anime
      - type: bind
        source: ./shows
        target: /data/shows
      - type: bind
        source: ./movies
        target: /data/movies
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.tail.sargun.ca
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  jellyfin_network:
    name: jellyfin_default
    driver: bridge
